; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=i686-unknown-unknown -mattr=+sse2 | FileCheck %s --check-prefixes=SDAG-X86
; RUN: llc < %s -fast-isel -fast-isel-abort=1 -mtriple=i686-unknown-unknown -mattr=+sse2 | FileCheck %s --check-prefixes=FAST-X86
; RUN: llc < %s -global-isel -global-isel-abort=1 -mtriple=i686-unknown-unknown -mattr=+sse2 | FileCheck %s --check-prefixes=GISEL-X86
; RUN: llc < %s -mtriple=x86_64-unknown-unknown -mattr=+sse2 | FileCheck %s --check-prefixes=X64
; RUN: llc < %s -fast-isel -fast-isel-abort=1 -mtriple=x86_64-unknown-unknown -mattr=+sse2 | FileCheck %s --check-prefixes=X64
; RUN: llc < %s -global-isel -global-isel-abort=1 -mtriple=x86_64-unknown-unknown -mattr=+sse2 | FileCheck %s --check-prefixes=GISEL-X64

define i128 @add_i128(i128 %x, i128 %y) nounwind {
; SDAG-X86-LABEL: add_i128:
; SDAG-X86:       # %bb.0:
; SDAG-X86-NEXT:    pushl %edi
; SDAG-X86-NEXT:    pushl %esi
; SDAG-X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; SDAG-X86-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; SDAG-X86-NEXT:    movl {{[0-9]+}}(%esp), %edx
; SDAG-X86-NEXT:    movl {{[0-9]+}}(%esp), %esi
; SDAG-X86-NEXT:    movl {{[0-9]+}}(%esp), %edi
; SDAG-X86-NEXT:    subl {{[0-9]+}}(%esp), %esi
; SDAG-X86-NEXT:    sbbl {{[0-9]+}}(%esp), %edi
; SDAG-X86-NEXT:    sbbl {{[0-9]+}}(%esp), %ecx
; SDAG-X86-NEXT:    sbbl {{[0-9]+}}(%esp), %edx
; SDAG-X86-NEXT:    addl $1, %esi
; SDAG-X86-NEXT:    adcl $0, %edi
; SDAG-X86-NEXT:    adcl $0, %ecx
; SDAG-X86-NEXT:    adcl $0, %edx
; SDAG-X86-NEXT:    movl %edi, 4(%eax)
; SDAG-X86-NEXT:    movl %esi, (%eax)
; SDAG-X86-NEXT:    movl %ecx, 8(%eax)
; SDAG-X86-NEXT:    movl %edx, 12(%eax)
; SDAG-X86-NEXT:    popl %esi
; SDAG-X86-NEXT:    popl %edi
; SDAG-X86-NEXT:    retl $4
;
; FAST-X86-LABEL: add_i128:
; FAST-X86:       # %bb.0:
; FAST-X86-NEXT:    pushl %edi
; FAST-X86-NEXT:    pushl %esi
; FAST-X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; FAST-X86-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; FAST-X86-NEXT:    movl {{[0-9]+}}(%esp), %edx
; FAST-X86-NEXT:    movl {{[0-9]+}}(%esp), %esi
; FAST-X86-NEXT:    movl {{[0-9]+}}(%esp), %edi
; FAST-X86-NEXT:    subl {{[0-9]+}}(%esp), %edi
; FAST-X86-NEXT:    sbbl {{[0-9]+}}(%esp), %esi
; FAST-X86-NEXT:    sbbl {{[0-9]+}}(%esp), %edx
; FAST-X86-NEXT:    sbbl {{[0-9]+}}(%esp), %ecx
; FAST-X86-NEXT:    addl $1, %edi
; FAST-X86-NEXT:    adcl $0, %esi
; FAST-X86-NEXT:    adcl $0, %edx
; FAST-X86-NEXT:    adcl $0, %ecx
; FAST-X86-NEXT:    movl %edi, (%eax)
; FAST-X86-NEXT:    movl %esi, 4(%eax)
; FAST-X86-NEXT:    movl %edx, 8(%eax)
; FAST-X86-NEXT:    movl %ecx, 12(%eax)
; FAST-X86-NEXT:    popl %esi
; FAST-X86-NEXT:    popl %edi
; FAST-X86-NEXT:    retl $4
;
; GISEL-X86-LABEL: add_i128:
; GISEL-X86:       # %bb.0:
; GISEL-X86-NEXT:    pushl %edi
; GISEL-X86-NEXT:    pushl %esi
; GISEL-X86-NEXT:    movl {{[0-9]+}}(%esp), %edi
; GISEL-X86-NEXT:    movl {{[0-9]+}}(%esp), %esi
; GISEL-X86-NEXT:    movl {{[0-9]+}}(%esp), %edx
; GISEL-X86-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; GISEL-X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; GISEL-X86-NEXT:    subl $1, %edi
; GISEL-X86-NEXT:    sbbl $0, %esi
; GISEL-X86-NEXT:    sbbl $0, %edx
; GISEL-X86-NEXT:    sbbl $0, %ecx
; GISEL-X86-NEXT:    subl %edi, %eax
; GISEL-X86-NEXT:    movl {{[0-9]+}}(%esp), %edi
; GISEL-X86-NEXT:    sbbl %esi, %edi
; GISEL-X86-NEXT:    movl {{[0-9]+}}(%esp), %esi
; GISEL-X86-NEXT:    sbbl %edx, %esi
; GISEL-X86-NEXT:    movl {{[0-9]+}}(%esp), %edx
; GISEL-X86-NEXT:    sbbl %ecx, %edx
; GISEL-X86-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; GISEL-X86-NEXT:    movl %eax, (%ecx)
; GISEL-X86-NEXT:    movl %edi, 4(%ecx)
; GISEL-X86-NEXT:    movl %esi, 8(%ecx)
; GISEL-X86-NEXT:    movl %edx, 12(%ecx)
; GISEL-X86-NEXT:    popl %esi
; GISEL-X86-NEXT:    popl %edi
; GISEL-X86-NEXT:    retl
;
; X64-LABEL: add_i128:
; X64:       # %bb.0:
; X64-NEXT:    movq %rdx, %rax
; X64-NEXT:    subq %rdi, %rax
; X64-NEXT:    sbbq %rsi, %rcx
; X64-NEXT:    addq $1, %rax
; X64-NEXT:    adcq $0, %rcx
; X64-NEXT:    movq %rcx, %rdx
; X64-NEXT:    retq
;
; GISEL-X64-LABEL: add_i128:
; GISEL-X64:       # %bb.0:
; GISEL-X64-NEXT:    movq %rdx, %rax
; GISEL-X64-NEXT:    subq $1, %rdi
; GISEL-X64-NEXT:    sbbq $0, %rsi
; GISEL-X64-NEXT:    subq %rdi, %rax
; GISEL-X64-NEXT:    sbbq %rsi, %rcx
; GISEL-X64-NEXT:    movq %rcx, %rdx
; GISEL-X64-NEXT:    retq
  %t0 = sub i128 %x, 1
  %t1 = sub i128 %y, %t0
  ret i128 %t1
}
