; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -global-isel=0                    -mtriple=x86_64-linux-gnu | FileCheck %s --check-prefixes=X64
; RUN: llc < %s -fast-isel -fast-isel-abort=1     -mtriple=x86_64-linux-gnu | FileCheck %s --check-prefixes=X64
; RUN: llc < %s -global-isel -global-isel-abort=1 -mtriple=x86_64-linux-gnu | FileCheck %s --check-prefixes=GISEL-X64
; RUN: llc < %s -global-isel=0                    -mtriple=i686-linux-gnu   | FileCheck %s --check-prefixes=X86,SDAG-X86
; RUN: llc < %s -fast-isel -fast-isel-abort=1     -mtriple=i686-linux-gnu   | FileCheck %s --check-prefixes=X86,FAST-X86
; RUN: llc < %s -global-isel -global-isel-abort=1 -mtriple=i686-linux-gnu   | FileCheck %s --check-prefixes=GISEL-X86

define i1 @test_mul_i1(i1 %arg1, i1 %arg2) {
; X64-LABEL: test_mul_i1:
; X64:       # %bb.0:
; X64-NEXT:    movl %edi, %eax
; X64-NEXT:    # kill: def $al killed $al killed $eax
; X64-NEXT:    mulb %sil
; X64-NEXT:    retq
;
; GISEL-X64-LABEL: test_mul_i1:
; GISEL-X64:       # %bb.0:
; GISEL-X64-NEXT:    movsbl %dil, %eax
; GISEL-X64-NEXT:    imulb %sil
; GISEL-X64-NEXT:    retq
;
; X86-LABEL: test_mul_i1:
; X86:       # %bb.0:
; X86-NEXT:    movzbl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    mulb {{[0-9]+}}(%esp)
; X86-NEXT:    retl
;
; GISEL-X86-LABEL: test_mul_i1:
; GISEL-X86:       # %bb.0:
; GISEL-X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; GISEL-X86-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; GISEL-X86-NEXT:    cbtw
; GISEL-X86-NEXT:    imulb %cl
; GISEL-X86-NEXT:    retl
  %ret = mul i1 %arg1, %arg2
  ret i1 %ret
}


define i8 @test_mul_i8(i8 %arg1, i8 %arg2) {
; X64-LABEL: test_mul_i8:
; X64:       # %bb.0:
; X64-NEXT:    movl %edi, %eax
; X64-NEXT:    # kill: def $al killed $al killed $eax
; X64-NEXT:    mulb %sil
; X64-NEXT:    retq
;
; GISEL-X64-LABEL: test_mul_i8:
; GISEL-X64:       # %bb.0:
; GISEL-X64-NEXT:    movsbl %dil, %eax
; GISEL-X64-NEXT:    imulb %sil
; GISEL-X64-NEXT:    retq
;
; X86-LABEL: test_mul_i8:
; X86:       # %bb.0:
; X86-NEXT:    movzbl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    mulb {{[0-9]+}}(%esp)
; X86-NEXT:    retl
;
; GISEL-X86-LABEL: test_mul_i8:
; GISEL-X86:       # %bb.0:
; GISEL-X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; GISEL-X86-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; GISEL-X86-NEXT:    cbtw
; GISEL-X86-NEXT:    imulb %cl
; GISEL-X86-NEXT:    retl
  %ret = mul i8 %arg1, %arg2
  ret i8 %ret
}

define i16 @test_mul_i16(i16 %arg1, i16 %arg2) nounwind {
; SDAG-X64-LABEL: test_mul_i16:
; SDAG-X64:       # %bb.0:
; SDAG-X64-NEXT:    movl %edi, %eax
; SDAG-X64-NEXT:    imull %esi, %eax
; SDAG-X64-NEXT:    # kill: def $ax killed $ax killed $eax
; SDAG-X64-NEXT:    retq
;
; FAST-X64-LABEL: test_mul_i16:
; FAST-X64:       # %bb.0:
; FAST-X64-NEXT:    movl %edi, %eax
; FAST-X64-NEXT:    imulw %si, %ax
; FAST-X64-NEXT:    # kill: def $ax killed $ax killed $eax
; FAST-X64-NEXT:    retq
;
; GISEL-X64-LABEL: test_mul_i16:
; GISEL-X64:       # %bb.0:
; GISEL-X64-NEXT:    movl %esi, %eax
; GISEL-X64-NEXT:    imulw %di, %ax
; GISEL-X64-NEXT:    # kill: def $ax killed $ax killed $eax
; GISEL-X64-NEXT:    retq
;
; X86-LABEL: test_mul_i16:
; X86:       # %bb.0:
; X86-NEXT:    movzwl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    imulw {{[0-9]+}}(%esp), %ax
; X86-NEXT:    retl
;
; GISEL-X86-LABEL: test_mul_i16:
; GISEL-X86:       # %bb.0:
; GISEL-X86-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; GISEL-X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; GISEL-X86-NEXT:    imulw %cx, %ax
; GISEL-X86-NEXT:    # kill: def $ax killed $ax killed $eax
; GISEL-X86-NEXT:    retl
  %ret = mul i16 %arg1, %arg2
  ret i16 %ret
}

define i32 @test_mul_i32(i32 %arg1, i32 %arg2) nounwind {
; X64-LABEL: test_mul_i32:
; X64:       # %bb.0:
; X64-NEXT:    movl %edi, %eax
; X64-NEXT:    imull %esi, %eax
; X64-NEXT:    retq
;
; GISEL-X64-LABEL: test_mul_i32:
; GISEL-X64:       # %bb.0:
; GISEL-X64-NEXT:    movl %esi, %eax
; GISEL-X64-NEXT:    imull %edi, %eax
; GISEL-X64-NEXT:    retq
;
; X86-LABEL: test_mul_i32:
; X86:       # %bb.0:
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    imull {{[0-9]+}}(%esp), %eax
; X86-NEXT:    retl
;
; GISEL-X86-LABEL: test_mul_i32:
; GISEL-X86:       # %bb.0:
; GISEL-X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; GISEL-X86-NEXT:    imull {{[0-9]+}}(%esp), %eax
; GISEL-X86-NEXT:    retl
  %ret = mul i32 %arg1, %arg2
  ret i32 %ret
}

define i64 @test_mul_i64(i64 %arg1, i64 %arg2) nounwind {
; X64-LABEL: test_mul_i64:
; X64:       # %bb.0:
; X64-NEXT:    movq %rdi, %rax
; X64-NEXT:    imulq %rsi, %rax
; X64-NEXT:    retq
;
; GISEL-X64-LABEL: test_mul_i64:
; GISEL-X64:       # %bb.0:
; GISEL-X64-NEXT:    movq %rsi, %rax
; GISEL-X64-NEXT:    imulq %rdi, %rax
; GISEL-X64-NEXT:    retq
;
; SDAG-X86-LABEL: test_mul_i64:
; SDAG-X86:       # %bb.0:
; SDAG-X86-NEXT:    pushl %esi
; SDAG-X86-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; SDAG-X86-NEXT:    movl {{[0-9]+}}(%esp), %esi
; SDAG-X86-NEXT:    movl %ecx, %eax
; SDAG-X86-NEXT:    mull %esi
; SDAG-X86-NEXT:    imull {{[0-9]+}}(%esp), %ecx
; SDAG-X86-NEXT:    addl %ecx, %edx
; SDAG-X86-NEXT:    imull {{[0-9]+}}(%esp), %esi
; SDAG-X86-NEXT:    addl %esi, %edx
; SDAG-X86-NEXT:    popl %esi
; SDAG-X86-NEXT:    retl
;
; FAST-X86-LABEL: test_mul_i64:
; FAST-X86:       # %bb.0:
; FAST-X86-NEXT:    pushl %esi
; FAST-X86-NEXT:    movl {{[0-9]+}}(%esp), %esi
; FAST-X86-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; FAST-X86-NEXT:    movl %ecx, %eax
; FAST-X86-NEXT:    mull %esi
; FAST-X86-NEXT:    imull {{[0-9]+}}(%esp), %ecx
; FAST-X86-NEXT:    addl %ecx, %edx
; FAST-X86-NEXT:    imull {{[0-9]+}}(%esp), %esi
; FAST-X86-NEXT:    addl %esi, %edx
; FAST-X86-NEXT:    popl %esi
; FAST-X86-NEXT:    retl
;
; GISEL-X86-LABEL: test_mul_i64:
; GISEL-X86:       # %bb.0:
; GISEL-X86-NEXT:    pushl %edi
; GISEL-X86-NEXT:    pushl %esi
; GISEL-X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; GISEL-X86-NEXT:    movl {{[0-9]+}}(%esp), %edx
; GISEL-X86-NEXT:    movl {{[0-9]+}}(%esp), %esi
; GISEL-X86-NEXT:    imull %eax, %esi
; GISEL-X86-NEXT:    movl %eax, %ecx
; GISEL-X86-NEXT:    imull %edx, %ecx
; GISEL-X86-NEXT:    movl {{[0-9]+}}(%esp), %edi
; GISEL-X86-NEXT:    imull %edx, %edi
; GISEL-X86-NEXT:    addl %edi, %esi
; GISEL-X86-NEXT:    mull %edx
; GISEL-X86-NEXT:    addl %esi, %edx
; GISEL-X86-NEXT:    movl %ecx, %eax
; GISEL-X86-NEXT:    popl %esi
; GISEL-X86-NEXT:    popl %edi
; GISEL-X86-NEXT:    retl
  %ret = mul i64 %arg1, %arg2
  ret i64 %ret
}
